### ISSUE TITLE
Error conecting to Trakt Lists

### ISSUE THREAD

**Issue by tulkarxxx** [pymedusa/medusa.github.io#287]
2021-01-28 13:29:56 ERROR    Thread_0 :: [] Could not connect to Trakt service: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
Traceback (most recent call last):
  File "/app/medusa/medusa/show/recommendations/trakt.py", line 143, in fetch_popular_shows
    trending_shows.append(self._create_recommended_show(
  File "</app/medusa/ext/decorator.py:decorator-gen-52>", line 2, in _create_recommended_show
  File "/app/medusa/ext/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
    return self.get_or_create(
  File "/app/medusa/ext/dogpile/cache/region.py", line 1042, in get_or_create
    with Lock(
  File "/app/medusa/ext/dogpile/lock.py", line 185, in __enter__
    return self._enter()
  File "/app/medusa/ext/dogpile/lock.py", line 87, in _enter
    value = value_fn()
  File "/app/medusa/ext/dogpile/cache/region.py", line 977, in get_value
    value = self._get_from_backend(key)
  File "/app/medusa/ext/dogpile/cache/region.py", line 1264, in _get_from_backend
    return self._parse_serialized_from_backend(
  File "/app/medusa/ext/dogpile/cache/region.py", line 1221, in _parse_serialized_from_backend
    metadata = json.loads(bytes_metadata)
  File "/usr/lib/python3.8/json/__init__.py", line 343, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

**Comment by medariox** [comment]
https://github.com/pymedusa/Medusa/issues/9094#issuecomment-766845722
