### ISSUE TITLE
WARNING  SEARCHQUEUE-BACKLOG-44217 :: [] Unhashable type encountered

### ISSUE THREAD

**Issue by idmanager100** [pymedusa/medusa.github.io#433]
2022-12-13 18:52:26 WARNING  SEARCHQUEUE-BACKLOG-44217 :: [] Unhashable type encountered. Please report this warning to the developers.
TypeError('Object of type Episode is not JSON serializable')
Traceback (most recent call last):
  File "/app/medusa/medusa/ws/__init__.py", line 41, in json
    return json.dumps(self.content)
  File "/usr/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Episode is not JSON serializable

**Comment by medariox** [comment]
Please open issues here: https://github.com/pymedusa/Medusa/issues
